# Shell variables
# Generated by 'wal'
wallpaper='/home/atwosi/.config/wpg/wallpapers/blazar.jpg'

# Special
background='#0f0f1a'
foreground='#9dcecc'
cursor='#9dcecc'

# Colors
color0='#0f0f1a'
color1='#476A90'
color2='#92385F'
color3='#A6648F'
color4='#97556F'
color5='#C46E9D'
color6='#809277'
color7='#9dcecc'
color8='#97556f'
color9='#476A90'
color10='#92385F'
color11='#A6648F'
color12='#97556F'
color13='#C46E9D'
color14='#809277'
color15='#9dcecc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
